/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Bean.GoodStudentBean;
import Bean.RegistrationBean;
import Bean.StudentBean;
import java.util.Comparator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author huutuan
 */
public class ViewReportGoodStudentFrm extends javax.swing.JFrame {
    
    private DefaultTableModel tmListGoodStudent;
    private List<GoodStudentBean> goodStudentBeans;
    private GoodStudentBean goodStudentBean;
    private String id;
    
    /**
     * Creates new form ViewReportGoodStudentFrm
     */
    public ViewReportGoodStudentFrm() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        tmListGoodStudent = (DefaultTableModel)tblListGoodStudent.getModel();
        
        GoodStudentBean gStuB = new GoodStudentBean();
        goodStudentBeans = gStuB.getAllGoodStudent();
        
        if(goodStudentBeans.size()==0){
            lblMessage.setText("Không có sinh viên giỏi nào!!");
        }else{
            tmListGoodStudent.setRowCount(0);
            for(GoodStudentBean goodStudentBean : goodStudentBeans){
                tmListGoodStudent.addRow(goodStudentBean.toObjects());
            }
        }                           
    }
    
    public StudentBean detailStudentAction(){        
        StudentBean stuB = new StudentBean();
        return stuB.getStudentByID(id);
    }
    
    public List<RegistrationBean> detailRegisAction(){
        RegistrationBean regB = new RegistrationBean();
        StudentBean stuB = new StudentBean();
        
        List<RegistrationBean> res = regB.getAllResByStudentID(stuB.getStudentByID(id).getId());
        res.sort(new Comparator<RegistrationBean>(){
            @Override
            public int compare(RegistrationBean o1, RegistrationBean o2) {
                return o1.getClassBean().getSubjectBean().getId().compareTo(o2.getClassBean().getSubjectBean().getId());
            }
            
        });
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListGoodStudent = new javax.swing.JTable();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("List of Good Student");

        tblListGoodStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Student name", "Academic Year", "Semester", "Sum credits", "Medium of Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListGoodStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListGoodStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListGoodStudent);

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(282, 282, 282))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblListGoodStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListGoodStudentMouseClicked
        // TODO add your handling code here:
        int row = tblListGoodStudent.getSelectedRow();
        if(row>=0 && row<tblListGoodStudent.getRowCount()){
            id = tblListGoodStudent.getValueAt(row, 0).toString();
            System.out.println(id);
            ViewDetailStudentFrm detai = new ViewDetailStudentFrm(this, true);
            detai.setVisible(true);
        }
    }//GEN-LAST:event_tblListGoodStudentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReportGoodStudentFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReportGoodStudentFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReportGoodStudentFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReportGoodStudentFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReportGoodStudentFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblListGoodStudent;
    // End of variables declaration//GEN-END:variables
}
